### ISSUE TITLE
Little instruction on adding to Zabbix

### ISSUE THREAD

**Issue by anglebra** [selivan/https-ssl-cert-check-zabbix#4]
Greetings!

It appears your instructions are incomplete - it does not detail adding this as a template into Zabbix. Nor does it provide instruction on what the $1, $2, $3 and $4 mean in your userparameters example.

I encourage trying a little harder in getting this to work with Zabbix completely, with integrations to add hosts to monitor from within the web interface rather than the script.

It's a great script! Just very much incomplete when it comes to integration. I would hope a project like this being in the Zabbix website as a recommended and popular solution be made FOR Zabbix rather than have the "option" for Zabbix.

**Comment by selivan** [comment]
Hey @anglebra 

I had no idea that this script is listed somewhere on Zabbix website. That explains the number of stars :)

`userparameters_ssl_cert_check.conf` has description of parameters, but I also added the description to the README.

There are a lot of options of where domains and ports for cert check may come from: low-level discovery, macros, hostname, etc. That is why I do not provide a template example - I can not create a universal one. Creating the one that suits your particular case should be quite straightforward.

**Comment by anglebra** [comment]
Your readme isn't updated yet - and is still vague as to the variables in your userparam file.

I don't appreciate the snarky attitude. The lay of the land might be clear for you, but to me there's still lots of fog.

I encourage you to design your scripts with varying levels of experience in mind.
________________________________

**Comment by selivan** [comment]
Updated README:

> Usage
> `ssl_cert_check.sh valid|expire <hostname or IP> <port> [domain for TLS SNI] [check timeout (seconds)]`

Parameters description in `userparameters_ssl_cert_check.conf`:

> `# Parameters:`
> `# <hostname or IP> <port> [domain for TLS SNI] [check timeout]`

I added to the README link to user parameters chapter in zabbix manual for unexperienced users. But I don't want to add a whole zabbix guide to it. This solution requires user to be familiar with basic zabbix features, like user parameters, items, triggers and templates. Since that level of knowledge is required to use zabbix anyway, I don't think that's a problem.

**Comment by anglebra** [comment]
You are still being very vague though. Provide an actual example instead of saying host or sni. Imagine I have no idea what SNI is.
Also imagine that I have no idea what $1 through 4 means.

also imagine I have no idea how to invoke the script and do this properly in zabbix. Does one have to create an item for system run? Does this run basically created the domain name or does it have to run physically on a host?

you have to remember that the internet is full of people with varying levels of experience, and I would hope that you would want just about anybody to pick up your script and know exactly what to do moving forward.

You see, I'm a systems administrator. I have to make sure that my documentation is in such a way that everybody and their grandmother can understand it. that basically anybody can pick up my work and carry it out exactly as I have, say I quit or was on vacation...

when you don't inform your audience on your product, you make them resent you. Then they look for a completely different solution with more explanations that paint a clearer picture. by not including this documentation you are deliberately sabotaging your own product and making it look like crap.

I'm just saying the script works fine, but your explanations flat-out suck.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by anglebra** [comment]
Toadd to the fact that one needs basic understanding of zabbix, I am just starting to use a pex and I'm building it from the ground up to suit my environment. everybody uses addicts differently. Everybody has their own way of doing things. I don't know how you are doing things. I can guess but I'll probably be wrong, because you have not yet explained yourself or your product. Does that make sense?

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by anglebra** [comment]
Sorry, apparently I can't type.


To add to the fact that one needs basic understanding of zabbix, I am just starting to use it, and am building it from the ground up to suit my environment. everybody uses Zabbix differently. Everybody has their own way of doing things. I don't know how you are doing things. I can guess but I'll probably be wrong, because you have not yet explained yourself or your product. Does that make sense?

Better.


Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by selivan** [comment]
I completely agree that good technical documentation is important. Writing good documentation is hard because it should have 2 opposite properties: detailed enough to describe everything about the software and concise enough so that user can understand it with minimum amount of time and effort.

Every document has some requirements for the audience level. Book on basic algebra requires reader to know arithmetics. Book on math. analysis requires reader to be familiar with elementary mathematics.

A surgical tool does not come with a complete human anatomy atlas and a guide on performing medical operations. The one buying that tool should already know human anatomy and many other things, and if he/she doesn't - than he/she should learn that before using surgical tools.

This is a SSL/TLS certificate validity and monitoring script, for use with Zabbix or standalone in Unix shell. The person trying to use this script should know basic things about TLS(including SNI), cryptography with public and private keys, computer networks, Unix shell. If this script is used with Zabbix - that person should know basic things about Zabbix as well, such as templates, items, triggers, user parameters(including what is $1 - $4).

If he/she doesn't know that things - then he/she will not be able to use this script anyway, before he/she learns that. And I should not try to cram all this  information(basically a beginners guide on systems administration) into a small tool README. Zabbix manual, Google and stackoverflow will do much better job than I will.

**Comment by selivan** [comment]
@anglebra on this note let's agree to disagree. Thanks for pointing this out, I updated the README to be more clear.
